# Generated by Django 4.2.1 on 2023-06-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.PositiveIntegerField()),
                ('nome', models.CharField(max_length=55)),
                ('sobrenome', models.CharField(max_length=55)),
                ('email', models.EmailField(max_length=100)),
                ('materia', models.CharField(max_length=55)),
                ('media_nota', models.FloatField()),
            ],
        ),
    ]
