# Generated by Django 4.1.7 on 2023-03-28 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=55)),
                ('sobrenome', models.CharField(max_length=55)),
                ('idade', models.IntegerField()),
                ('sexo', models.CharField(max_length=9)),
            ],
        ),
    ]
